theme: minima
title: Be Humble
author: Theepeekaa
email: theepeekaa@gmail.com
description: "Being humble to other humans is the best way of spreading humanity"
  

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
